# Gemfile used to create win32_wrapper

source :rubygems

gem 'ocra', '~> 1.3.0'
gem 'rake'

gem 'gosu', '~> 0.7.41'
gem 'ray', '~> 0.2.0'
gem 'chipmunk', '~> 5.3.4.5'
gem 'texplay', '= 0.3.5' # 0.4.2 is the latest, but isn't a binary gem and compiling is non-trivial. 0.3.5 isn't 1.9.3 compatible.